# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3z1Yc9VexWeY6B325qMllY8vnWMt54s
"""

# app.py
import json
import numpy as np
import pandas as pd
import streamlit as st

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler, PowerTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import folium
from streamlit_folium import st_folium

# -----------------------
# Konfigurasi halaman
# -----------------------
st.set_page_config(
    page_title="Stunting — Regression, Klasifikasi & Clustering",
    layout="wide"
)

# ======================
# Utils (helper umum)
# ======================
CENTROIDS = {
    "ACEH": (4.695, 96.749), "SUMATERA UTARA": (2.115, 99.545),
    "SUMATERA BARAT": (-0.739, 100.800), "RIAU": (0.293, 101.707),
    "KEPULAUAN RIAU": (0.917, 104.446), "JAMBI": (-1.610, 103.613),
    "SUMATERA SELATAN": (-3.319, 104.914), "BENGKULU": (-3.577, 102.346),
    "LAMPUNG": (-4.558, 105.406), "KEP. BANGKA BELITUNG": (-2.741, 106.440),
    "BANTEN": (-6.405, 106.064), "DKI JAKARTA": (-6.175, 106.827),
    "JAWA BARAT": (-6.889, 107.640), "JAWA TENGAH": (-7.150, 110.140),
    "D I YOGYAKARTA": (-7.795, 110.369), "JAWA TIMUR": (-7.536, 112.238),
    "BALI": (-8.341, 115.092), "NUSA TENGGARA BARAT": (-8.652, 117.361),
    "NUSA TENGGARA TIMUR": (-8.657, 121.079), "KALIMANTAN BARAT": (-0.132, 111.095),
    "KALIMANTAN TENGAH": (-1.681, 113.382), "KALIMANTAN SELATAN": (-3.092, 115.283),
    "KALIMANTAN TIMUR": (0.538, 116.419), "KALIMANTAN UTARA": (2.838, 117.388),
    "SULAWESI UTARA": (1.493, 124.840), "GORONTALO": (0.699, 122.446),
    "SULAWESI TENGAH": (-1.430, 121.445), "SULAWESI BARAT": (-2.844, 119.232),
    "SULAWESI SELATAN": (-3.668, 119.974), "SULAWESI TENGGARA": (-4.144, 122.174),
    "MALUKU": (-3.238, 130.145), "MALUKU UTARA": (1.570, 127.808),
    "PAPUA": (-4.269, 138.080), "PAPUA BARAT": (-1.336, 133.174),
    "PAPUA BARAT DAYA": (-0.876, 131.255), "PAPUA PEGUNUNGAN": (-4.095, 138.944),
    "PAPUA SELATAN": (-8.493, 140.401), "PAPUA TENGAH": (-3.360, 135.500),
}

def norm_name(s: str) -> str:
    s = str(s).upper().strip()
    s = s.replace("D. I.", "D I ").replace("DI YOGYAKARTA", "D I YOGYAKARTA")
    s = s.replace("KEPULAUAN BANGKA BELITUNG", "KEP. BANGKA BELITUNG")
    return s

def ensure_cols(df: pd.DataFrame, required: list):
    missing = [c for c in required if c not in df.columns]
    if missing:
        st.error(f"Kolom wajib hilang: {missing}")
        st.stop()

def try_load_geojson(uploaded_file):
    if uploaded_file is None:
        return None, None
    try:
        gj = json.load(uploaded_file)
        props = gj["features"][0]["properties"]
        name_field = None
        for k in props:
            if k.lower() in ["provinsi","name","province","prov_name"]:
                name_field = k; break
        if name_field is None:
            name_field = list(props.keys())[0]
        for ft in gj["features"]:
            ft["properties"]["prov_norm"] = norm_name(ft["properties"][name_field])
        return gj, "prov_norm"
    except Exception as e:
        st.warning(f"Gagal membaca GeoJSON: {e}")
        return None, None

def choropleth_from_df(df_map, category_col, score_col=None, geojson=None, geo_key="prov_norm"):
    """Warna provinsi sesuai kategori; fallback ke marker jika GeoJSON tidak ada."""
    m = folium.Map(location=[-2.5, 118.0], zoom_start=5, tiles="cartodbpositron")
    cat_palette = {
        "Sehat": "#2E8B57",
        "Sedang": "#F0AD4E",
        "Tidak Sehat": "#D9534F",
        "Sejahtera (Stunting Rendah)": "#2E8B57",
        "Rentan (Stunting Tinggi)": "#D9534F"
    }
    if geojson is not None:
        lookup = df_map.set_index(geo_key)[category_col].to_dict()
        def style_fn(feature):
            prov = feature["properties"].get(geo_key, "")
            color = cat_palette.get(lookup.get(prov, ""), "#BDBDBD")
            return {"fillColor": color, "color": "white", "weight": 1, "fillOpacity": 0.9}
        folium.GeoJson(
            data=geojson,
            name="Map",
            style_function=style_fn,
            tooltip=folium.features.GeoJsonTooltip(fields=[geo_key], aliases=["Provinsi:"])
        ).add_to(m)
    else:
        for _, r in df_map.iterrows():
            prov = r[geo_key]
            latlon = CENTROIDS.get(prov)
            if not latlon:
                continue
            color = cat_palette.get(r[category_col], "#888888")
            text_score = "" if (score_col is None or score_col not in r) else f"<br/>Skor: {r[score_col]:.2f}"
            html = f"<b>{r['Provinsi']}</b><br/>{category_col}: <b>{r[category_col]}</b>{text_score}"
            folium.CircleMarker(
                location=latlon, radius=8, color="white", weight=1,
                fill=True, fill_color=color, fill_opacity=0.9,
                tooltip=r['Provinsi'], popup=folium.Popup(html, max_width=280)
            ).add_to(m)
    return m

# --- helper robust preprocessing ---
def _winsorize(df, cols, q_low=0.05, q_hi=0.95):
    df = df.copy()
    for c in cols:
        lo, hi = df[c].quantile(q_low), df[c].quantile(q_hi)
        df[c] = df[c].clip(lo, hi)
    return df

def _best_kmeans(X, k, n_init_total=50, random_state=42):
    """Multi-start KMeans: pilih model dengan silhouette terbaik."""
    from sklearn.metrics import silhouette_score
    best = None
    best_sil = -1
    rng = np.random.RandomState(random_state)
    seeds = rng.randint(0, 10_000, size=n_init_total)
    for s in seeds:
        km = KMeans(n_clusters=k, n_init=1, random_state=int(s))
        lab = km.fit_predict(X)
        if len(set(lab)) < k:
            continue
        sil = silhouette_score(X, lab)
        if sil > best_sil:
            best_sil, best = sil, (km, lab)
    return best[0], best[1], best_sil

def _composite_score(dfz, w):
    """Skor sejahtera berbobot: dfz = fitur terstandarisasi, w = dict bobot."""
    s = 0
    for k, a in w.items():
        s = s + a * dfz[k]
    return s

# ======================
# Sidebar
# ======================
st.sidebar.title("Navigasi")
page = st.sidebar.selectbox(
    "Pilih fitur:",
    ["1) Regression (Random Forest)", "2) Klasifikasi Sehat vs Tidak Sehat", "3) CLUSTERING STUNTING"]
)

st.sidebar.markdown("---")
st.sidebar.caption("Upload data utama (CSV). Disarankan data hasil cleaning/normalisasi.")
uploaded_csv = st.sidebar.file_uploader("Upload CSV", type=["csv"])
geojson_file = st.sidebar.file_uploader("(Opsional) Upload GeoJSON provinsi", type=["geojson","json"])

if uploaded_csv is None:
    st.info("Silakan upload CSV terlebih dahulu.")
    st.stop()

df = pd.read_csv(uploaded_csv)
if 'Provinsi' in df.columns:
    df['prov_norm'] = df['Provinsi'].map(norm_name)
geojson, geo_key = try_load_geojson(geojson_file)

# ======================
# Page 1: Regression (Form Prediksi saja)
# ======================
if page.startswith("1"):
    st.title("🔮 Regression — Prediksi Stunting (Random Forest)")
    req_cols = [
        'IPM','Kemiskinan_Persen','Akses_Sanitasi','Akses_Air_Minum',
        'Pengangguran_Persen','Pengeluaran_Kapita','PDRB','Stunting_2023'
    ]
    ensure_cols(df, req_cols)

    # Latih model di belakang layar (tanpa metrik/importance)
    X = df[['IPM','Kemiskinan_Persen','Akses_Sanitasi','Akses_Air_Minum',
            'Pengangguran_Persen','Pengeluaran_Kapita','PDRB']].copy()
    y = df['Stunting_2023'].copy()
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)
    rf = RandomForestRegressor(
        n_estimators=200, max_depth=6,
        min_samples_split=3, min_samples_leaf=2, random_state=42
    ).fit(X_tr, y_tr)

    # Hanya form prediksi
    st.subheader("Form Prediksi")
    c1, c2, c3 = st.columns(3)
    with c1:
        ipm = st.number_input("IPM", value=float(np.round(X['IPM'].mean(),2)))
        kem = st.number_input("Kemiskinan (%)", value=float(np.round(X['Kemiskinan_Persen'].mean(),2)))
    with c2:
        san = st.number_input("Akses Sanitasi (%)", value=float(np.round(X['Akses_Sanitasi'].mean(),2)))
        air = st.number_input("Akses Air Minum (%)", value=float(np.round(X['Akses_Air_Minum'].mean(),2)))
    with c3:
        peng = st.number_input("Pengangguran (%)", value=float(np.round(X['Pengangguran_Persen'].mean(),2)))
        kapita = st.number_input("Pengeluaran/Kapita (ribu/tahun)", value=float(np.round(X['Pengeluaran_Kapita'].mean(),1)))
        pdrb = st.number_input("PDRB", value=float(np.round(X['PDRB'].mean(),1)))

    if st.button("Prediksi Stunting"):
        xin = pd.DataFrame([{
            "IPM": ipm, "Kemiskinan_Persen": kem, "Akses_Sanitasi": san,
            "Akses_Air_Minum": air, "Pengangguran_Persen": peng,
            "Pengeluaran_Kapita": kapita, "PDRB": pdrb
        }])
        yhat = rf.predict(xin)[0]
        st.success(f"🎯 Prediksi Stunting: **{yhat:.2f}%**")

# ======================
# Page 2: Klasifikasi Sehat vs Tidak Sehat (k=3 → binarisasi)
# ======================
elif page.startswith("2"):
    st.title("🏥 Klasifikasi Sehat vs Tidak Sehat (K-Means k=3 → binarisasi) — Peta Indonesia")

    req_cols = [
        'Provinsi','Akses_Sanitasi','Akses_Air_Minum','IPM',
        'Pengangguran_Persen','Kemiskinan_Persen','PDRB'
    ]
    ensure_cols(df, req_cols)

    # 1) Siapkan & rapikan data
    base = df[['Provinsi','Akses_Sanitasi','Akses_Air_Minum','IPM',
               'Pengangguran_Persen','Kemiskinan_Persen','PDRB']].dropna().copy()
    base['prov_norm'] = base['Provinsi'].map(norm_name)

    # log PDRB + winsorize
    base['PDRB_log'] = np.log1p(base['PDRB'].clip(lower=0))
    feat_cls = ['Akses_Sanitasi','Akses_Air_Minum','IPM','Pengangguran_Persen','Kemiskinan_Persen','PDRB_log']
    base = _winsorize(base, feat_cls, q_low=0.05, q_hi=0.95)

    # 2) Yeo-Johnson + standardize
    pj = PowerTransformer(method='yeo-johnson', standardize=True)
    Xz = pj.fit_transform(base[feat_cls])
    dfz = pd.DataFrame(Xz, columns=feat_cls, index=base.index)

    # 3) KMeans k=3 (multi-start → silhouette terbaik)
    km, labels, sil = _best_kmeans(dfz.values, k=3, n_init_total=60, random_state=42)
    base['Cluster'] = labels

    # 4) Skor sejahtera berbobot (IPM+; Sanitasi+; Air+; PDRB_log+; Kemiskinan-; Pengangguran-)
    weights = {
        'IPM': 0.35, 'Akses_Sanitasi': 0.20, 'Akses_Air_Minum': 0.15,
        'PDRB_log': 0.10, 'Kemiskinan_Persen': -0.15, 'Pengangguran_Persen': -0.15
    }
    base['Skor_Sejahtera'] = _composite_score(dfz, weights)

    # 5) Cluster terbaik (rata-rata skor tertinggi)
    mean_skor = base.groupby('Cluster')['Skor_Sejahtera'].mean().sort_values(ascending=False)
    order = list(mean_skor.index)   # [terbaik, menengah, terburuk]
    label_map = {order[0]: 'Sehat', order[1]: 'Tidak Sehat', order[2]: 'Tidak Sehat'}
    base['Kategori'] = base['Cluster'].map(label_map)

    # 6) Sanity override ringan (mengunci provinsi anchor)
    ipm_hi = base['IPM'].quantile(0.85)
    pov_lo = base['Kemiskinan_Persen'].quantile(0.15)
    mask_anchor = (base['IPM'] >= ipm_hi) & (base['Kemiskinan_Persen'] <= pov_lo)
    base.loc[mask_anchor, 'Kategori'] = 'Sehat'

    # 7) Tabel & Peta
    st.dataframe(
        base[['Provinsi','Kategori','Cluster','Skor_Sejahtera'] + feat_cls]
        .sort_values(['Kategori','Provinsi']),
        use_container_width=True
    )
    m = choropleth_from_df(base, category_col='Kategori', score_col='Skor_Sejahtera',
                           geojson=geojson, geo_key='prov_norm')
    st_folium(m, width=None, height=560)

# ======================
# Page 3: CLUSTERING STUNTING (k=3, tanpa metrik)
# ======================
else:
    st.title("🍼 CLUSTERING STUNTING")

    req_cols = [
        'Provinsi','Stunting_2023','IPM','Kemiskinan_Persen','Pengangguran_Persen',
        'Akses_Sanitasi','Akses_Air_Minum','PDRB','Rata_Lama_Sekolah'
    ]
    ensure_cols(df, req_cols)

    # 1) Fitur untuk klaster TANPA stunting (stunting hanya untuk penamaan)
    feat0 = ['IPM','Kemiskinan_Persen','Pengangguran_Persen',
             'Akses_Sanitasi','Akses_Air_Minum','Rata_Lama_Sekolah','PDRB']
    data = df[['Provinsi','Stunting_2023'] + feat0].dropna().copy()
    data['prov_norm'] = data['Provinsi'].map(norm_name)

    # log PDRB + winsorize
    if (data['PDRB'] > 0).all():
        data['PDRB_log'] = np.log1p(data['PDRB'])
        feat_clu = [c for c in feat0 if c != 'PDRB'] + ['PDRB_log']
    else:
        feat_clu = feat0
    data = _winsorize(data, feat_clu, q_low=0.05, q_hi=0.95)

    # 2) Yeo-Johnson + standardize
    pj2 = PowerTransformer(method='yeo-johnson', standardize=True)
    Xz = pj2.fit_transform(data[feat_clu])

    # 3) KMeans k=3 multi-start
    km, lab, sil = _best_kmeans(Xz, k=3, n_init_total=60, random_state=42)
    data['Cluster'] = lab

    # 4) Label dari rata-rata stunting (rendah→tinggi) + sanity override
    st_mean = data.groupby('Cluster')['Stunting_2023'].mean().sort_values()
    order = list(st_mean.index)  # [rendah, sedang, tinggi]
    label_map = {
        order[0]: 'Sejahtera (Stunting Rendah)',
        order[1]: 'Sedang',
        order[2]: 'Rentan (Stunting Tinggi)'
    }
    data['Kategori_Stunting'] = data['Cluster'].map(label_map)

    q20 = data['Stunting_2023'].quantile(0.20)
    q80_ipm = data['IPM'].quantile(0.80)
    mask_good = (data['Stunting_2023'] <= q20) & (data['IPM'] >= q80_ipm)
    data.loc[mask_good, 'Kategori_Stunting'] = 'Sejahtera (Stunting Rendah)'

    st.dataframe(
        data[['Provinsi','Stunting_2023','Kategori_Stunting'] + feat_clu]
        .sort_values('Stunting_2023'),
        use_container_width=True
    )

    m = choropleth_from_df(
        data.rename(columns={'Kategori_Stunting':'Kategori'}),
        category_col='Kategori',
        geojson=geojson, geo_key='prov_norm'
    )
    st_folium(m, width=None, height=560)

    # Opsional: PCA scatter (boleh dihapus kalau tak perlu)
    try:
        import plotly.express as px
        pca = PCA(n_components=2, random_state=42)
        p2 = pca.fit_transform(Xz)
        data['PCA1'], data['PCA2'] = p2[:,0], p2[:,1]
        fig = px.scatter(
            data, x='PCA1', y='PCA2', color='Kategori',
            hover_name='Provinsi',
            color_discrete_map={
                'Sejahtera (Stunting Rendah)':'#2E8B57',
                'Sedang':'#F0AD4E',
                'Rentan (Stunting Tinggi)':'#D9534F'
            },
            width=900, height=520
        )
        st.plotly_chart(fig, use_container_width=True)
    except Exception:
        pass